/* Generated by Cython 0.26 */

#ifndef __PYX_HAVE__text2image
#define __PYX_HAVE__text2image


#ifndef __PYX_HAVE_API__text2image

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void text2image(char const *, char const *);

#endif /* !__PYX_HAVE_API__text2image */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittext2image(void);
#else
PyMODINIT_FUNC PyInit_text2image(void);
#endif

#endif /* !__PYX_HAVE__text2image */
